---
title: "Experiences"
about:
  template: marquee
  image-shape: round
  image-width: 20em
---

## Research

**2024 - 2026: Post-doctoral researcher in machine learning.** \[[LIFO](https://www.univ-orleans.fr/lifo/?lang=en)\]**\
**Developing new algorithms and AIs for groundwater levels forecasting as part of the project [Junon](https://www.brgm.fr/en/programme/junon-digital-twins-working-natural-resources) for the [BRGM](https://www.brgm.fr/en) with the help of python and pytorch.

## Communications

**2024 - 2025 : Oral presentation at the Physics-informed learning and large models day ([GDR IASIS](https://gdr-iasis.cnrs.fr/reunions/journee-apprentissage-informe-par-la-physique-et-grands-modeles/)).** \[[LIFO](https://www.univ-orleans.fr/lifo/?lang=en)\]\
The presentation topic was groundwater prediction and the use of physical equations with unobservable variables in recurrent neural networks.\
**Abstract :** The management of water reserves is becoming a crucial issue in the context of climate change. In order to predict the future availability of groundwater, the BRGM uses the GARDENIA software, based on a simplified physical model using reservoirs and siphon mechanisms, integrating both observable (such as precipitation or water level) and unobservable variables (such as half-life factors or the equilibrium factor between flow and percolation). The aim of our work is to predict groundwater levels while maintaining consistency with the GARDENIA model. To achieve this, we developed a physics-informed deep learning model, integrating the GARDENIA equations as constraints during learning.

**2023 - 2024: Oral presentation at the European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases ([ECML-PKDD2024](https://ecmlpkdd.org/2024/)).** \[[GREYC](https://www.greyc.fr/en/home/)\]\
Presentation of WaveLSea (Wave top-k random-d Lineage Search), an interactive algorithm for pattern exploration, and the soothsayers, a novel paradigm for the evaluation of interactive algorithm.\
**Abstract :** The method Wave Top-k Random-d Lineage Search (WaveLSea) which guides an expert through data mining results according to her interest. The method exploits expert feedback, combined with the relation between patterns to spread the expert’s interest. It avoids the typical feature definition step commonly used in interactive data mining which limits the flexibility of the discovery process. We empirically demonstrate that WaveLSea returns the most relevant results for the user’s subjective interest. Even with imperfect feedback, WaveLSea behavior remains robust as it primarily still delivers most interesting results during experiments on graph-structured data. In order to assess the robustness of the method we design novel oracles called soothsayers giving imperfect feedback.

**2023 - 2024: Oral presentation at the French Society of Chemoinformatics** **([SFCi](https://ggmm-sfci-lille.com/)).** \[[GREYC](https://www.greyc.fr/en/home/)\]\
Presentation of the SubGaph Pattern Explorer (SGPEx) package as well as its user interface, the Wave Top-k Random-d Family Search algorithm (WTRFS), and the creation of a structured space of pharmacophore influenced by the expert interactions.

**2023 - 2024: Oral presentation at the [XKDD](http://xkdd2023.isti.cnr.it/) workshop at [ECML-PKDD2023](https://2023.ecmlpkdd.org/).** \[[GREYC](https://www.greyc.fr/en/home/)\]\
Presentation of a novel interactive pattern mining method, WTRFS, as well as the novel procedures to evaluate them.

**2022 - 2023: Poster presentation at Spring workshop on Mining and Learning 2023 ([SMiLe 2023](https://dtai.cs.kuleuven.be/static/events/SML23/index.php)).** \[[GREYC](https://www.greyc.fr/en/home/)\]

**2022 - 2023: Oral presentation at the Conference of Knowledge Extraction and Management ([EGC](https://egc2023.sciencesconf.org/)).** \[[GREYC](https://www.greyc.fr/en/home/)\]

**2021 - 2022: Poster presentation at the Chemical Summer School of Strasbourg.** \[[GREYC](https://www.greyc.fr/en/home/)\]

**2021 - 2022: Oral presentation at the Symposium on Intelligent Data Analysis ([IDA](https://link.springer.com/book/10.1007/978-3-031-01333-1)).** \[[GREYC](https://www.greyc.fr/en/home/)\]\
Symposium on data, knowledge representation and machine learning.\
Presentation of a novel local contrast selector aiming to select outstanding patterns in data regarding the sibling context.\
**Abstract :** The purpose of pattern mining is to help experts understand their data. Following the assumption that an analyst expects neighbouring patterns to show similar behavior, we investigate the interestingness of a pattern given its neighborhood. We define a new way of selecting *outstanding* patterns, based on an order relation between patterns and a given quality score. An outstanding pattern shows only small syntactic variations compared to its neighbors but deviates strongly in quality. Using several supervised quality measures, we show experimentally that only very few patterns turn out to be outstanding. We also illustrate our approach with patterns mined from molecular data.

**2021 - 2022: Poster presentation at the Conference of Knowledge Extraction and Management ([EGC](https://egc2022.univ-tours.fr/))** \[[GREYC](https://www.greyc.fr/en/home/)\]\
Conference going from data creation and management, to machine learning and data mining.

**2021 - 2022: Poster presentation at the French Society of Chemoinformatics ([SFCi](https://ggmm-sfci-lille.com/)).** \[[GREYC](https://www.greyc.fr/en/home/)\]\
Symposium addressing feature extraction, machine learning, visualization and more.\
Presenting my first work going from molecules to the creation of a data structure of their biological behaviors allowing us to find outlyers.

------------------------------------------------------------------------

## Other Conferences

**2024 - 2025: Conference of Knowledge Extraction and Management ([EGC](https://egc2023.sciencesconf.org/)).** \[[LIFO](https://www.univ-orleans.fr/lifo/?lang=en)\]

**2024 - 2025: Symposium "[Digital twins: from creation to communication](https://www.lestudium-ias.com/events/digital-twins-creation-communication)".** \[[LIFO](https://www.univ-orleans.fr/lifo/?lang=en)\]\
From the conception and creation of digital twins to the importance of state-of-the art visualization techniques and their influence on our decision, without forgetting to address the question of using them for various tasks as forecasting or clustering.

------------------------------------------------------------------------

## Engineering

**2021 - 2024: Creation of the research tool [SGPEx](https://hal.science/hal-04057516/).** \[[GREYC](https://www.greyc.fr/en/home/)\]\
The SubGraph Pattern Explorer is a C++ package with a JS UI designed to guide experts through a subgraph pattern language. This tools allows to exploit the partial order relation of the subgraph inclusion to structure the pattern language. It allows the application of several quality measures and implements novel ones as the [Oustanding Pattern Selector](https://hal.science/hal-03658500v1/file/IDA2022-E-LEHEMBRE.pdf) (OPS), also known as the Pharmacophore Activity Delta selector (PAD), and the Eclat measure. This tools also implements the Wave Top-k Random-d Family Search (WTRFS) exploration algorithm designed to guide experts in an unknown subgraph pattern language without any prior.

**2023 - 2024: Supervision of an internship in second year of engineering.** \[[GREYC](https://www.greyc.fr/en/home/), [EnsiCaen](https://www.ensicaen.fr/?lang=en)\]\
The internship was focused on the development of soothsayers, a novel way of evaluating interactive pattern mining methods. Soothsayers are oracles making controlled errors and simulating the learning curve of a user. Originally developed for [WaveLSea](https://hal.science/hal-04589011v1), soothsayers allows us to evaluate the robustness of interactive pattern mining algorithms. The soothsayers have been added to an implementation of LeTSip and Dispale and have given satisfying results.

**2022 - 2023: Supervision of an internship in second year of masters degree.** \[[GREYC](https://www.greyc.fr/en/home/), [University of Caen Normandy](https://www.unicaen.fr/)\]\
The intership was focused on the creation of a User Interface for the SGPEx package. The intern had to: add a websocket to the pre-existing code with [boost beast](https://www.boost.org/doc/libs/1_82_0/libs/beast/doc/html/index.html), create a JavaScript web server using [Node.js](https://nodejs.org/en) for the HTML content and [Cytoscape.js](https://js.cytoscape.org/) for the graph visualization, and run experiments on the WTRFS algorithm.

**2018 - 2019: Developer internship.** \[[NORSEMAN Interactive](https://www.linkedin.com/company/norseman-interactive/?originalSubdomain=fr)\]\
Development of a mobile game engine for interactive story telling on Android. Including the User Interface design, sound design, parameters, history management, rollback, etc... The development included the use of Unity, C#, and several other tools.

------------------------------------------------------------------------

## Collective responsibilities and others

**2025 - 2026: program committee member of IDA2026.**\
Participation to the biding and peer reviewing phase of IDA.

**2023 - 2024: Participation to quality scheme workshop.**\
Workshop aiming to establish a quality scheme about research and innovation for the university of Caen Normandy.

**2023 - 2024: Organization of the Doctoral School PhD's Day.** \[[ED MIIS](https://ed-miis.normandie-univ.fr/en/)\]\
Prospecting for speakers at the PhD conference days of the MIIS doctoral school.

**2023 - 2024: Participation at the science feast of Caen.** \[[GREYC](https://www.greyc.fr/en/home/)\]\
Creation of a vulgarization game for the science feast around recommendation systems and pharmacophores in chemoinformatics ([OpenBadge](https://openbadgefactory.com/v1/assertion/9dc932d022fbc9118cd72e67f1a745f627ccee77)).

**2022 - 2024: Member of the university research commission.** \[[University of Caen Normandy](https://www.unicaen.fr/)\]

**2022 - 2024: Delegate at the doctoral school.** \[[ED MIIS](https://ed-miis.normandie-univ.fr/en/)\]

**2020 - 2021: Student delegate.** \[[University of Rouen](https://www.univ-rouen.fr/)\]

**2018 - 2020: Private teacher.** \[[Numéro1 Scolarité](https://www.numero1-scolarite.com/)\]

**2018 - 2019: Student delegate.** \[[University of Rouen](https://www.univ-rouen.fr/)\]

**2017 - 2019: Mentor in algorithmic.** \[[ATACC](https://www.facebook.com/atacc.madrillet/)\]

------------------------------------------------------------------------

## Article reviews

**International conferences I reviewed for:**

-   **AAAI 2026**
-   **PAKDD 2023**

**International workshops I reviewed for:**

-   **MLSA 2024**

-   **MLSA 2023**
